### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [GiorgioGhisotti/gotcha#2]
Hi @GiorgioGhisotti , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by GiorgioGhisotti** [comment]
Hi! Thank you for your interest, honestly I didn't expect this - I already asked a friend to draw a logo in her spare time but if you'd still like to submit your own design I'd be happy to consider it.

Be aware that this started as a university project, so I don't know if I'll keep developing it for long - though if people are interested I'd love to expand it.

**Comment by zularizal** [comment]
Hi @GiorgioGhisotti , this is the design logo for your project. Logo Which do you like, 1 or 2?
And what color do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/55666855-93c81e00-587e-11e9-8464-016cd115d70f.png)

**Comment by GiorgioGhisotti** [comment]
Hi, I think I prefer number 1, the blue version. If you send me the png files (or a vector file) I'll add them to the app as soon as I have time. Thanks!

**Comment by zularizal** [comment]
Hi, I have sent pull request. #3 

And also I have uploaded the logo to the drive. Check this link
https://drive.google.com/open?id=1z0gy8_Scy7iqccggdI6l3xGkVfE7pgnK

And I have thickened the side of the camera icon on the logo, so that it will appear on the small display.

**Comment by GiorgioGhisotti** [comment]
I merged the request, thank you!
